development:
  adapter: postgresql
  encoding: unicode
  database: toy_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: toy_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: toy_production
  pool: 5
  username:
  password:
